<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product Group NA</name>
   <tag></tag>
   <elementGuidId>05de5d2c-299f-4f66-9f7b-0d62c199d628</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='EditView']/table[2]/tbody/tr/td[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row-fluid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--None--No ProductMFP B&amp;WMFP ColorLP B&amp;WLP ColorPriportMarketing CampaignsWide FormatPP B&amp;WPP ColorDTGAir PurifierRicoh ProjectorIWBUCSMeeting Room SolutionBEN QLogitechSamsungFolding MachineShredder MachineCollector Machine@RemoteService ContractThermal Business (IMS)ITS Hardware (BSD)ITS Solution (BSD)Ricoh Software (MKT)Document Management Software (MKT)Cost Management Software (MKT)Device Management Software (MKT)Document Management System (DTS)Business Process Management (DTS)Outsourcing Service (DTS)Scanning Service (DTS)Fever Screening (CSD)CCTV (CSD)R-Pass (CSD)R-Track (CSD)Help Desk Service (CSD)Device Management Service (CSD)OtherWork From Home SolutionTV Screen--None----None--No ProductMFP B&amp;WMFP ColorLP B&amp;WLP ColorPriportMarketing CampaignsWide FormatPP B&amp;WPP ColorDTGAir PurifierRicoh ProjectorIWBUCSMeeting Room SolutionBEN QLogitechSamsungFolding MachineShredder MachineCollector Machine@RemoteService ContractThermal Business (IMS)ITS Hardware (BSD)ITS Solution (BSD)Ricoh Software (MKT)Document Management Software (MKT)Cost Management Software (MKT)Device Management Software (MKT)Document Management System (DTS)Business Process Management (DTS)Outsourcing Service (DTS)Scanning Service (DTS)Fever Screening (CSD)CCTV (CSD)R-Pass (CSD)R-Track (CSD)Help Desk Service (CSD)Device Management Service (CSD)OtherWork From Home SolutionTV Screen</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EditView&quot;)/table[@class=&quot;table table-bordered blockContainer showInlineTable equalSplit&quot;]/tbody[1]/tr[1]/td[@class=&quot;fieldValue medium borderRedColor&quot;]/div[@class=&quot;row-fluid&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='EditView']/table[2]/tbody/tr/td[2]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[2]/div</value>
   </webElementXpaths>
</WebElementEntity>
